steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=Movies-Automation"]
    args: ["install", "."]
    id: "docker-build"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/helloworld:${TAG_NAME}", "."]
    id: "docker-build"
